name: demo

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull request number'
        required: true
        type: number

permissions:
  contents: read
  pull-requests: read

jobs:
  demo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Get PR head ref
        id: pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_json=$(gh api repos/${{ github.repository }}/pulls/${{ inputs.pr_number }})
          head_ref=$(echo "$pr_json" | jq -r '.head.ref')
          head_sha=$(echo "$pr_json" | jq -r '.head.sha')
          echo "head_ref=$head_ref" >> "$GITHUB_OUTPUT"
          echo "head_sha=$head_sha" >> "$GITHUB_OUTPUT"

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.CI_BOT_APP_ID }}
          private-key: ${{ secrets.CI_BOT_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v6
        with:
          ref: ${{ steps.pr.outputs.head_sha }}
          token: ${{ steps.app-token.outputs.token }}

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install VHS
        run: |
          sudo apt update
          sudo apt install -y ffmpeg ttyd
          go install github.com/charmbracelet/vhs@5262b81b590d3908a9e2d63cf06603ec0d0ae78e

      - name: Set up demo environment
        run: docs/demo-setup.sh

      - name: Generate demo GIF
        env:
          CLICOLOR_FORCE: "1"
          COLORTERM: truecolor
          CI: ""
        run: |
          vhs docs/demo.tape
          mv demo.gif docs/demo.gif

      - name: Commit updated demo GIF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/demo.gif
          if ! git diff --cached --quiet; then
            git commit -m "chore: update demo.gif"
            git push origin HEAD:${{ steps.pr.outputs.head_ref }}
          fi

      - name: Post demo comment
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405
        with:
          header: demo
          number: ${{ inputs.pr_number }}
          recreate: true
          message: |
            ### 🎬 Demo

            ![demo](https://raw.githubusercontent.com/${{ github.repository }}/${{ steps.pr.outputs.head_ref }}/docs/demo.gif?t=${{ github.run_id }})

            Generated by [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).

            _Run `gh workflow run demo.yml -R ${{ github.repository }} -f pr_number=${{ inputs.pr_number }}` to regenerate._
